spring.application.name=NearKart

# =========================
# DATABASE CONFIGURATION
# =========================

spring.datasource.url=jdbc:mysql://localhost:3306/nearkart_db
spring.datasource.username=root
spring.datasource.password=Devipriya8055


# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# =========================
# JWT CONFIGURATION
# =========================

jwt.secret=${JWT_SECRET}